OBJS= stat.o laserparameters.o imuparameters.o logutils.o transformation2.o

APPS= transformation3_test stat_test graph_test

LDFLAGS+=  -lm -lpthread
CPPFLAGS+= -DFSLINE  

-include ../global.mk
-include ../build_tools/Makefile.generic-shared-object-notest



