-include ../global.mk

OBJS= cfgreader.o cmdargsreader.o linefilereader.o 
COBJS= timeval_ops.o 
APPS= cfgreader_test


LDFLAGS+= 
CPPFLAGS+= -DFSLINE 


-include ../build_tools/Makefile.generic-shared-object

