-include ./global.mk
#normal
SUBDIRS= ipc utils_global utils_ipc math_stuff ipcInterfaces configSender libserial-0.5.2 logger laser imu flightcontrol matcher cmatcher odometry localizer
LDFLAGS+=
CPPFLAGS+=

-include ./build_tools/Makefile.subdirs

