OBJS= cmatcher.o histcmatcher.o mrcmatcher.o histmrcmatcher.o
APPS= cmatcher_test

LDFLAGS+=  -lm -lqc_math_stuff -lqc_matcher 
CPPFLAGS+= -DFSLINE 

-include ../global.mk
-include ../build_tools/Makefile.generic-shared-object-notest



