/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/UAVTeam/catkin_ws/src/imu_broadcast/msgs/raw_imu.msg
 *
 */


#ifndef IMU_BROADCAST_MESSAGE_RAW_IMU_H
#define IMU_BROADCAST_MESSAGE_RAW_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_broadcast
{
template <class ContainerAllocator>
struct raw_imu_
{
  typedef raw_imu_<ContainerAllocator> Type;

  raw_imu_()
    : xacc(0)
    , yacc(0)
    , zacc(0)
    , xgyro(0)
    , ygyro(0)
    , zgyro(0)  {
    }
  raw_imu_(const ContainerAllocator& _alloc)
    : xacc(0)
    , yacc(0)
    , zacc(0)
    , xgyro(0)
    , ygyro(0)
    , zgyro(0)  {
    }



   typedef int16_t _xacc_type;
  _xacc_type xacc;

   typedef int16_t _yacc_type;
  _yacc_type yacc;

   typedef int16_t _zacc_type;
  _zacc_type zacc;

   typedef int16_t _xgyro_type;
  _xgyro_type xgyro;

   typedef int16_t _ygyro_type;
  _ygyro_type ygyro;

   typedef int16_t _zgyro_type;
  _zgyro_type zgyro;




  typedef boost::shared_ptr< ::imu_broadcast::raw_imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_broadcast::raw_imu_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct raw_imu_

typedef ::imu_broadcast::raw_imu_<std::allocator<void> > raw_imu;

typedef boost::shared_ptr< ::imu_broadcast::raw_imu > raw_imuPtr;
typedef boost::shared_ptr< ::imu_broadcast::raw_imu const> raw_imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_broadcast::raw_imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_broadcast::raw_imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_broadcast

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'imu_broadcast': ['/home/UAVTeam/catkin_ws/src/imu_broadcast/msgs']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_broadcast::raw_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_broadcast::raw_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_broadcast::raw_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_broadcast::raw_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_broadcast::raw_imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_broadcast::raw_imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_broadcast::raw_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3507f0b63f5790cbc052576b2a56f94a";
  }

  static const char* value(const ::imu_broadcast::raw_imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3507f0b63f5790cbULL;
  static const uint64_t static_value2 = 0xc052576b2a56f94aULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_broadcast::raw_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_broadcast/raw_imu";
  }

  static const char* value(const ::imu_broadcast::raw_imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_broadcast::raw_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 xacc\n\
int16 yacc\n\
int16 zacc\n\
int16 xgyro\n\
int16 ygyro\n\
int16 zgyro\n\
";
  }

  static const char* value(const ::imu_broadcast::raw_imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_broadcast::raw_imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xacc);
      stream.next(m.yacc);
      stream.next(m.zacc);
      stream.next(m.xgyro);
      stream.next(m.ygyro);
      stream.next(m.zgyro);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct raw_imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_broadcast::raw_imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_broadcast::raw_imu_<ContainerAllocator>& v)
  {
    s << indent << "xacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xacc);
    s << indent << "yacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yacc);
    s << indent << "zacc: ";
    Printer<int16_t>::stream(s, indent + "  ", v.zacc);
    s << indent << "xgyro: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xgyro);
    s << indent << "ygyro: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ygyro);
    s << indent << "zgyro: ";
    Printer<int16_t>::stream(s, indent + "  ", v.zgyro);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_BROADCAST_MESSAGE_RAW_IMU_H
